// /quote — generated by Bot Studio
const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('quote')
    .setDescription('Quote one or more Discord messages by pasting their links')
    .addStringOption(opt =>
      opt.setName('links')
         .setDescription('Paste message links separated by spaces (max 10)')
         .setRequired(true)
    ),

  async execute(interaction) {
    await interaction.deferReply({ ephemeral: false });

    const raw    = interaction.options.getString('links');
    const linkRe = /https?:\/\/(?:ptb\.|canary\.)?discord(?:app)?\.com\/channels\/(\d+)\/(\d+)\/(\d+)/g;
    const links  = (raw.match(linkRe) || []).slice(0, 10);

    if (!links.length) {
      return interaction.editReply('❌ No valid Discord message links found.');
    }

    const parseLink = url => {
      const m = url.match(/channels\/(\d+)\/(\d+)\/(\d+)/);
      return m ? { channelId: m[2], messageId: m[3] } : null;
    };

    let first = true;

    for (const link of links) {
      const parsed = parseLink(link);
      if (!parsed) {
        const err = `❌ Invalid link: ${link}`;
        if (first) { await interaction.editReply(err); first = false; }
        else await interaction.followUp({ content: err, ephemeral: false });
        continue;
      }

      try {
        const channel = await interaction.client.channels.fetch(parsed.channelId);
        if (!channel || !channel.isTextBased()) throw new Error('Channel not accessible');
        const msg = await channel.messages.fetch(parsed.messageId);

        const tag     = `${msg.author.username}#${msg.author.discriminator}`;
        const dateStr = new Date(msg.createdTimestamp).toLocaleString('en-US', {
          month: 'numeric', day: 'numeric', year: 'numeric',
          hour: 'numeric', minute: '2-digit', second: '2-digit', hour12: true
        });

        let out = `**${tag}** — ${dateStr}`;
        if (msg.content) out += `\n${msg.content}`;

        if (msg.attachments && msg.attachments.size > 0) {
          out += '\\n';
          for (const att of msg.attachments.values()) {
            out += `\\nAttachments: 📎 [${att.name || 'file'}](${att.url})`;
          }
        }
        out += `\\n\\n Original: <#${msg.channelId}> 🌊`;

        if (first) { await interaction.editReply(out); first = false; }
        else await interaction.followUp({ content: out, ephemeral: false });

      } catch (err) {
        const errMsg = `❌ Could not fetch message: ${link}`;
        if (first) { await interaction.editReply(errMsg); first = false; }
        else await interaction.followUp({ content: errMsg, ephemeral: false });
      }
    }
  },
};
