// /quote — generated by Bot Studio
const { SlashCommandBuilder } = require('discord.js');

module.exports = {
  data: new SlashCommandBuilder()
    .setName('quote')
    .setDescription('Quote one or more Discord messages by pasting their links')
    .addStringOption(opt =>
      opt.setName('links')
         .setDescription('Paste message links separated by spaces (max 5)')
         .setRequired(true)
    ),

  async execute(interaction) {
    await interaction.deferReply({ ephemeral: false });

    const raw   = interaction.options.getString('links');
    const links = raw.trim().split(/\s+/).slice(0, 5);

    // Regex to parse Discord message links
    const linkRe = /https:\/\/(?:ptb\.|canary\.)?discord(?:app)?\.com\/channels\/(\d+)\/(\d+)\/(\d+)/;

    const lines = [];

    for (const link of links) {
      const m = link.match(linkRe);
      if (!m) { lines.push(`⚠️ Invalid link: ${link}`); continue; }

      const [, guildId, channelId, messageId] = m;

      try {
        const channel = await interaction.client.channels.fetch(channelId);
        if (!channel || !channel.isTextBased()) {
          lines.push(`⚠️ Can't access channel for: ${link}`);
          continue;
        }

        const msg = await channel.messages.fetch(messageId);

        const author    = `**${msg.author.tag}**`;
        const content   = msg.content || '*(no text content)*';
        const ts        = `<t:${Math.floor(msg.createdTimestamp / 1000)}:f>`;
        lines.push(`> 💬 ${author} · ${ts}\n> ${content}\n> 🔗 ${link}`);
      } catch (err) {
        lines.push(`❌ Could not fetch message: ${link}`);
      }
    }

    const reply = lines.join('\n\n');
    await interaction.editReply(reply.length ? reply : '❌ No valid messages found.');
  },
};
