// /quote — generated by Bot Studio
const { createCommandBuilder } = require('../utils/builders');
const { AttachmentBuilder } = require('discord.js');

function unescapeVisibleNewlines(text) {
  if (!text) return '';
  return String(text)
    .replace(/\\r\\n/g, '\n')
    .replace(/\\n/g, '\n')
    .replace(/\\r/g, '\n');
}

module.exports = {
  data: createCommandBuilder({
    name: 'quote',
    description: 'Quote one or more Discord messages by pasting their links',
    configure: builder => builder.addStringOption(opt =>
      opt.setName('links')
         .setDescription('Paste message links separated by spaces (max 10)')
         .setRequired(true)
    ),
  }),

  async execute(interaction) {
    await interaction.deferReply({ ephemeral: false });

    const raw    = interaction.options.getString('links');
    const linkRe = /https?:\/\/(?:ptb\.|canary\.)?discord(?:app)?\.com\/channels\/(\d+)\/(\d+)\/(\d+)/g;
    const links  = (raw.match(linkRe) || []).slice(0, 10);

    if (!links.length) {
      return interaction.editReply('❌ No valid Discord message links found.');
    }

    const parseLink = url => {
      const m = url.match(/channels\/(\d+)\/(\d+)\/(\d+)/);
      return m ? { channelId: m[2], messageId: m[3] } : null;
    };
    const csvEscape = value => `"${String(value ?? '').replace(/"/g, '""')}"`;

    let first = true;
    const rows = [['input_link', 'status', 'author_tag', 'created_at', 'channel_id', 'message_id', 'content', 'attachment_urls']];

    for (const link of links) {
      const parsed = parseLink(link);
      if (!parsed) {
        const err = `❌ Invalid link: ${link}`;
        rows.push([link, 'invalid_link', '', '', '', '', '', '']);
        if (first) { await interaction.editReply(err); first = false; }
        else await interaction.followUp({ content: err, ephemeral: false });
        continue;
      }

      try {
        const channel = await interaction.client.channels.fetch(parsed.channelId);
        if (!channel || !channel.isTextBased()) throw new Error('Channel not accessible');
        const msg = await channel.messages.fetch(parsed.messageId);

        const tag     = `${msg.author.username}#${msg.author.discriminator}`;
        const dateStr = new Date(msg.createdTimestamp).toLocaleString('en-US', {
          month: 'numeric', day: 'numeric', year: 'numeric',
          hour: 'numeric', minute: '2-digit', second: '2-digit', hour12: true
        });

        const displayContent = unescapeVisibleNewlines(msg.content || '');

        let out = `**${tag}** — ${dateStr}`;
        if (displayContent) out += `\n${displayContent}`;

        if (msg.attachments && msg.attachments.size > 0) {
          out += '\n';
          for (const att of msg.attachments.values()) {
            out += `\nAttachments: 📎 [${att.name || 'file'}](${att.url})`;
          }
        }
        const attachmentUrls = msg.attachments && msg.attachments.size > 0
          ? [...msg.attachments.values()].map(att => att.url).join(' | ')
          : '';
        rows.push([
          link,
          'quoted',
          tag,
          dateStr,
          msg.channelId,
          msg.id,
          displayContent,
          attachmentUrls
        ]);
        out += `\n\n Original: <#${msg.channelId}> 🌊`;

        if (first) { await interaction.editReply(out); first = false; }
        else await interaction.followUp({ content: out, ephemeral: false });

      } catch (err) {
        const errMsg = `❌ Could not fetch message: ${link}`;
        rows.push([link, 'fetch_failed', '', '', parsed.channelId, parsed.messageId, '', '']);
        if (first) { await interaction.editReply(errMsg); first = false; }
        else await interaction.followUp({ content: errMsg, ephemeral: false });
      }
    }

    if (rows.length > 1) {
      const csv = rows.map(cols => cols.map(csvEscape).join(',')).join('\n');
      const file = new AttachmentBuilder(Buffer.from(csv, 'utf8'), { name: `quote-${Date.now()}.csv` });
      try {
        await interaction.user.send({
          content: '📄 CSV export of quote results:',
          files: [file],
        });
        await interaction.followUp({ content: '✅ Sent CSV export to your DMs.', ephemeral: true });
      } catch (_) {
        await interaction.followUp({
          content: '📄 CSV export of quote results:',
          files: [file],
          ephemeral: false
        });
      }
    }
  },
};
